package com.example.communigate.ximss.response_request;

import com.example.communigate.ximss.parts_of_ximss.XimssAddress;
import com.example.communigate.ximss.parts_of_ximss.XimssDate;
import com.example.communigate.ximss.parts_of_ximss.ximss_dictionary.PtyType;
import com.example.communigate.ximss.response.Mime;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.*;

@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JacksonXmlRootElement(localName = "EMail")
public class Email {

    @JacksonXmlProperty(localName = "From")
    private XimssAddress from;

    @JacksonXmlProperty(localName = "To")
    private XimssAddress to;

    @JacksonXmlProperty(localName = "Cc")
    private XimssAddress cc;

    @JacksonXmlProperty(localName = "Bcc")
    private XimssAddress bcc;

    @JacksonXmlProperty(localName = "Sender")
    private XimssAddress sender;

    @JacksonXmlProperty(localName = "Reply-To")
    private XimssAddress replyTo;

    @JacksonXmlProperty(localName = "Disposition-Notification-To")
    private XimssAddress dispositionNotificationTo;

    @JacksonXmlProperty(localName = "Resent-From")
    private XimssAddress resentFrom;

    @JacksonXmlProperty(localName = "Resent-To")
    private XimssAddress resentTo;

    @JacksonXmlProperty(localName = "Return-Receipt-To")
    private XimssAddress returnReceiptTo;

    @JacksonXmlProperty(localName = "Errors-To")
    private XimssAddress errorsTo;

    @JacksonXmlProperty(localName = "Return-Path")
    private String returnPath;

    @JacksonXmlProperty(localName = "Date")
    private XimssDate date;

    @JacksonXmlProperty(localName = "Resent-Date")
    private XimssDate resentDate;

    @JacksonXmlProperty(localName = "Pty")
    private PtyType pty;

    @JacksonXmlProperty(localName = "Received")
    private String received;
    @JacksonXmlProperty(localName = "Subject")
    private String subject;

    @JacksonXmlProperty(localName = "X-Mailer")
    private String xMailer;

    @JacksonXmlProperty(localName = "X-Autogenerated")
    private String xAutogenerated;

    @JacksonXmlProperty(localName = "Message-ID")
    private String messageId;

    @JacksonXmlProperty(localName = "In-Reply-To")
    private String inReplyTo;

    @JacksonXmlProperty(localName = "References")
    private String references;

    @JacksonXmlProperty(localName = "MIME")
    private Mime mime;

}

